# Generated by Django 5.2.11 on 2026-02-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='report',
        ),
    ]
